/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.Documentation;
import bpmn2.ExtensionAttributeValue;
import bpmn2.ExtensionDefinition;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link bpmn2.BaseElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BaseElementValidator {
	boolean validate();

	boolean validateExtensionValues(EList<ExtensionAttributeValue> value);
	boolean validateDocumentation(EList<Documentation> value);
	boolean validateExtensionDefinitions(EList<ExtensionDefinition> value);
	boolean validateId(String value);
	boolean validateAnyAttribute(FeatureMap value);
}
