/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.InputOutputBinding;
import bpmn2.InputOutputSpecification;
import bpmn2.Interface;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.CallableElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallableElementValidator {
	boolean validate();

	boolean validateSupportedInterfaceRefs(EList<Interface> value);
	boolean validateIoSpecification(InputOutputSpecification value);
	boolean validateIoBinding(EList<InputOutputBinding> value);
	boolean validateName(String value);
}
