/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.DataOutput;
import bpmn2.DataOutputAssociation;
import bpmn2.EventDefinition;
import bpmn2.OutputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.CatchEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CatchEventValidator {
	boolean validate();

	boolean validateDataOutputs(EList<DataOutput> value);
	boolean validateDataOutputAssociation(EList<DataOutputAssociation> value);
	boolean validateOutputSet(OutputSet value);
	boolean validateEventDefinitions(EList<EventDefinition> value);
	boolean validateEventDefinitionRefs(EList<EventDefinition> value);
	boolean validateParallelMultiple(boolean value);
}
