/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.Artifact;
import bpmn2.Choreography;
import bpmn2.ConversationAssociation;
import bpmn2.ConversationLink;
import bpmn2.ConversationNode;
import bpmn2.CorrelationKey;
import bpmn2.MessageFlow;
import bpmn2.MessageFlowAssociation;
import bpmn2.Participant;
import bpmn2.ParticipantAssociation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.Collaboration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollaborationValidator {
	boolean validate();

	boolean validateParticipants(EList<Participant> value);
	boolean validateMessageFlows(EList<MessageFlow> value);
	boolean validateArtifacts(EList<Artifact> value);
	boolean validateConversations(EList<ConversationNode> value);
	boolean validateConversationAssociations(ConversationAssociation value);
	boolean validateParticipantAssociations(EList<ParticipantAssociation> value);
	boolean validateMessageFlowAssociations(EList<MessageFlowAssociation> value);
	boolean validateCorrelationKeys(EList<CorrelationKey> value);
	boolean validateChoreographyRef(EList<Choreography> value);
	boolean validateConversationLinks(EList<ConversationLink> value);
	boolean validateIsClosed(boolean value);
	boolean validateName(String value);
}
