/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.CorrelationPropertyRetrievalExpression;
import bpmn2.ItemDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.CorrelationProperty}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorrelationPropertyValidator {
	boolean validate();

	boolean validateCorrelationPropertyRetrievalExpression(EList<CorrelationPropertyRetrievalExpression> value);
	boolean validateName(String value);
	boolean validateType(ItemDefinition value);
}
