/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.InputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.DataInput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataInputValidator {
	boolean validate();

	boolean validateInputSetWithOptional(EList<InputSet> value);
	boolean validateInputSetWithWhileExecuting(EList<InputSet> value);
	boolean validateInputSetRefs(EList<InputSet> value);
	boolean validateIsCollection(boolean value);
	boolean validateName(String value);
}
