/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.Assignment;
import bpmn2.FormalExpression;
import bpmn2.ItemAwareElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.DataAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataAssociationValidator {
	boolean validate();

	boolean validateSourceRef(EList<ItemAwareElement> value);
	boolean validateTargetRef(ItemAwareElement value);
	boolean validateTransformation(FormalExpression value);
	boolean validateAssignment(EList<Assignment> value);
}
