/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.InteractionNode;
import bpmn2.Message;

/**
 * A sample validator interface for {@link bpmn2.MessageFlow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageFlowValidator {
	boolean validate();

	boolean validateMessageRef(Message value);
	boolean validateName(String value);
	boolean validateSourceRef(InteractionNode value);
	boolean validateTargetRef(InteractionNode value);
}
