/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.ComplexBehaviorDefinition;
import bpmn2.DataInput;
import bpmn2.DataOutput;
import bpmn2.EventDefinition;
import bpmn2.Expression;
import bpmn2.ItemAwareElement;
import bpmn2.MultiInstanceBehavior;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.MultiInstanceLoopCharacteristics}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MultiInstanceLoopCharacteristicsValidator {
	boolean validate();

	boolean validateLoopCardinality(Expression value);
	boolean validateLoopDataInputRef(ItemAwareElement value);
	boolean validateLoopDataOutputRef(ItemAwareElement value);
	boolean validateInputDataItem(DataInput value);
	boolean validateOutputDataItem(DataOutput value);
	boolean validateComplexBehaviorDefinition(EList<ComplexBehaviorDefinition> value);
	boolean validateCompletionCondition(Expression value);
	boolean validateBehavior(MultiInstanceBehavior value);
	boolean validateIsSequential(boolean value);
	boolean validateNoneBehaviorEventRef(EventDefinition value);
	boolean validateOneBehaviorEventRef(EventDefinition value);
}
