/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.EndPoint;
import bpmn2.Interface;
import bpmn2.ParticipantMultiplicity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.Participant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParticipantValidator {
	boolean validate();

	boolean validateInterfaceRefs(EList<Interface> value);
	boolean validateEndPointRefs(EList<EndPoint> value);
	boolean validateParticipantMultiplicity(ParticipantMultiplicity value);
	boolean validateName(String value);
	boolean validateProcessRef(bpmn2.Process value);
}
