/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.Resource;
import bpmn2.ResourceAssignmentExpression;
import bpmn2.ResourceParameterBinding;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn2.ResourceRole}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceRoleValidator {
	boolean validate();

	boolean validateResourceRef(Resource value);
	boolean validateResourceParameterBindings(EList<ResourceParameterBinding> value);
	boolean validateResourceAssignmentExpression(ResourceAssignmentExpression value);
	boolean validateName(String value);
}
