/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmn2.validation;

import bpmn2.Expression;
import bpmn2.FlowNode;

/**
 * A sample validator interface for {@link bpmn2.SequenceFlow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceFlowValidator {
	boolean validate();

	boolean validateConditionExpression(Expression value);
	boolean validateIsImmediate(boolean value);
	boolean validateSourceRef(FlowNode value);
	boolean validateTargetRef(FlowNode value);
}
