/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmndi.validation;

import bpmndi.BPMNLabelStyle;
import bpmndi.BPMNPlane;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmndi.BPMNDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNDiagramValidator {
	boolean validate();

	boolean validatePlane(BPMNPlane value);
	boolean validateLabelStyle(EList<BPMNLabelStyle> value);
}
