/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmndi.validation;

import bpmn2.BaseElement;

import bpmndi.BPMNLabel;
import bpmndi.DiagramElement;
import bpmndi.MessageVisibleKind;

/**
 * A sample validator interface for {@link bpmndi.BPMNEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNEdgeValidator {
	boolean validate();

	boolean validateLabel(BPMNLabel value);
	boolean validateBpmnElement(BaseElement value);
	boolean validateMessageVisibleKind(MessageVisibleKind value);
	boolean validateSourceElement(DiagramElement value);
	boolean validateTargetElement(DiagramElement value);
}
