/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package bpmndi.validation;


/**
 * A sample validator interface for {@link bpmndi.Font}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FontValidator {
	boolean validate();

	boolean validateIsBold(boolean value);
	boolean validateIsItalic(boolean value);
	boolean validateIsStrikeThrough(boolean value);
	boolean validateIsUnderline(boolean value);
	boolean validateName(String value);
	boolean validateSize(float value);
}
